name: Compile on Commit

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      # ruleid: allowed-unsecure-commands
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v3
    - name: log untrusted output
      run: |

        # disable command workflow processing
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

        # log untrusted output
        echo "untrusted output"

        # enable workflow command processing
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    - name: Create folder
      run: |
        mkdir build 
        ls ${{ github.workspace }}
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: '9-2020-q2'
    - name: make
      run: make
      
    - name: Install srecord
      run: |
        sudo apt-get update
        sudo apt-get install srecord
        
    - name: Install java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - run: java -cp java make/hexToLsh.java
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        path: ${{ github.workspace }}/output
        name: EBiCS_build_${{ github.run_number }}
        retention-days: 10
